### ISSUE TITLE
Hello, world!

### ISSUE THREAD

**Issue by WardCunningham** [WardCunningham/postmatic#1]
I created this issue using Octokit!

**Comment by WardCunningham** [comment]
Followed the instructions in the javacript octokit docs. [github](https://github.com/octokit/octokit.js#octokitrest-endpoint-methods)

Crazy error without modification.
```
error: Uncaught (in promise) HttpError: Not Found
      const error = new RequestError(toErrorMessage(data), status, {
                    ^
    at https://cdn.skypack.dev/-/@octokit/request@v5.6.2-MAuQKzoBVLIGyjcIqJQp/dist=es2019,mode=imports/optimized/@octokit/request.js:81:21
    at async Job.doExecute (https://cdn.skypack.dev/-/bottleneck@v2.19.5-WnyfIkTTdKNNPUEySJVJ/dist=es2019,mode=imports/unoptimized/light.js:354:20)
 ```
Got this reply substituting login for "octokit". [github](https://github.com/WardCunningham/postmatic/blob/main/spike.js)
```
{
  status: 201,
  url: "https://api.github.com/repos/WardCunningham/postmatic/issues",
  headers: {
    "access-control-allow-origin": "*",
    "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLim...",
    "cache-control": "private, max-age=60, s-maxage=60",
    "content-length": "2155",
    "content-security-policy": "default-src 'none'",
    "content-type": "application/json; charset=utf-8",
    date: "Sun, 17 Apr 2022 20:34:58 GMT",
    etag: '"20db4980f37a00080a0e809370f1cb2b3aee6a7379be2efef056c62b6886327b"',
    "github-authentication-token-expiration": "2022-05-17 19:17:02 UTC",
    location: "https://api.github.com/repos/WardCunningham/postmatic/issues/1",
    "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
    server: "GitHub.com",
    "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
    vary: "Accept, Authorization, Cookie, X-GitHub-OTP, Accept-Encoding, Accept, X-Requested-With",
    "x-accepted-oauth-scopes": "",
    "x-content-type-options": "nosniff",
    "x-frame-options": "deny",
    "x-github-media-type": "github.v3; format=json",
    "x-github-request-id": "F1BF:6753:26B077:290E77:625C79F1",
    "x-oauth-scopes": "repo, user",
    "x-ratelimit-limit": "5000",
    "x-ratelimit-remaining": "4996",
    "x-ratelimit-reset": "1650231109",
    "x-ratelimit-resource": "core",
    "x-ratelimit-used": "4",
    "x-xss-protection": "0"
  },
  data: {
    url: "https://api.github.com/repos/WardCunningham/postmatic/issues/1",
    repository_url: "https://api.github.com/repos/WardCunningham/postmatic",
    labels_url: "https://api.github.com/repos/WardCunningham/postmatic/issues/1/labels{/name}",
    comments_url: "https://api.github.com/repos/WardCunningham/postmatic/issues/1/comments",
    events_url: "https://api.github.com/repos/WardCunningham/postmatic/issues/1/events",
    html_url: "https://github.com/WardCunningham/postmatic/issues/1",
    id: 1206479824,
    node_id: "I_kwDOHMQPj85H6WvQ",
    number: 1,
    title: "Hello, world!",
    user: {
      login: "WardCunningham",
      id: 12127,
      node_id: "MDQ6VXNlcjEyMTI3",
      avatar_url: "https://avatars.githubusercontent.com/u/12127?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/WardCunningham",
      html_url: "https://github.com/WardCunningham",
      followers_url: "https://api.github.com/users/WardCunningham/followers",
      following_url: "https://api.github.com/users/WardCunningham/following{/other_user}",
      gists_url: "https://api.github.com/users/WardCunningham/gists{/gist_id}",
      starred_url: "https://api.github.com/users/WardCunningham/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/WardCunningham/subscriptions",
      organizations_url: "https://api.github.com/users/WardCunningham/orgs",
      repos_url: "https://api.github.com/users/WardCunningham/repos",
      events_url: "https://api.github.com/users/WardCunningham/events{/privacy}",
      received_events_url: "https://api.github.com/users/WardCunningham/received_events",
      type: "User",
      site_admin: false
    },
    labels: [],
    state: "open",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: "2022-04-17T20:34:58Z",
    updated_at: "2022-04-17T20:34:58Z",
    closed_at: null,
    author_association: "OWNER",
    active_lock_reason: null,
    body: "I created this issue using Octokit!",
    closed_by: null,
    reactions: {
      url: "https://api.github.com/repos/WardCunningham/postmatic/issues/1/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: "https://api.github.com/repos/WardCunningham/postmatic/issues/1/timeline",
    performed_via_github_app: null
  }
}
```

**Comment by WardCunningham** [comment]
https://sudokuku.deno.dev/?.475..9....1....4...24...15.3........527.418........9.27...13...6....2....1..457.

**Comment by WardCunningham** [comment]
https://sudokuku.deno.dev/?.475..9....1....4...24...15.3........527.418........9.27...13...6....2....1..457.

**Comment by WardCunningham** [comment]
https://sudokuku.deno.dev/?18749.......28.9749247....8.79.41...4.......7...87.64.9.....7.8748.92.......87.93

**Comment by WardCunningham** [comment]
https://sudokuku.deno.dev/?.1......5..628...9.9...64..5..8..7...3..54......6.1...49...6..7...8..6...6.23...4

**Comment by WardCunningham** [comment]
https://sudokuku.deno.dev/?1...2...32...3...43...4...54...5...65...6...76...7...87...8...98...9...19...1...2

**Comment by WardCunningham** [comment]
https://sudokuku.deno.dev/?1.4.2.6.32.5.3.7.43.6.4.8.54.7.5.9.65.8.6.1.76.9.7.2.87.1.8.3.98.2.9.4.19.3.1.5.2

**Comment by WardCunningham** [comment]
https://sudokuku.deno.dev/?123456789456789123789123456234567891567891234891234567...........................

**Comment by WardCunningham** [comment]
https://sudokuku.deno.dev/?.2.9..1...3.1....8.9.5......6....34.8..3.9..6.47....2......7.8.4....3.1...9..6.5.
